name: Start release
on:
  workflow_dispatch:
    inputs:
      versionName:
        type: string
        required: true
jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Create release branch
        uses: peterjgrainger/action-create-branch@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'release/${{ github.event.inputs.versionName }}'
